### PR TITLE
fix no available capacity issure

### PR DESCRIPTION
**Pull request by shangsony**

### CODE REVIEW

**Comment by ljedrz** [comment]
Isn't this more or less the same as the closed https://github.com/ljedrz/pea2pea/pull/8? You haven't responded to my reasoning there (where I mentioned those limits can easily just be extended as much as you want in your `Config`), and I'd rather discuss introducing changes that aren't trivially resolved with adjusting configuration.

That being said, I might actually use an `UnboundedChannel` for the channels inside the protocols (in the handler objects), as the growth of their depth is bounded by the connection limits. If you'd like to perform this change just there (and without changes to docs), I'd likely accept it.

**Comment by shangsony** [comment]
By testing mpsc::unbounded_channel performs better than mpsc::channel in this Pea2Pea ，

 mpsc::unbounded_channel test result：
image

 mpsc::channel  test result：
image

test code：
use bytes::Bytes;
use once_cell::sync::Lazy;
use rand::{distributions::Standard, rngs::SmallRng, Rng, SeedableRng};
use tokio::time::sleep;
use tracing::*;
mod common;
use pea2pea::{
    protocols::{Reading, Writing},
    Config, Node, Pea2Pea,
};
use std::time::Duration;

use std::{convert::TryInto, io, net::SocketAddr, time::Instant};

const NUM_MESSAGES: usize = 10_000;
const MSG_SIZE: usize = 128 * 1024;

static RANDOM_BYTES: Lazy<Bytes> = Lazy::new(|| {
    Bytes::from(
        (&mut SmallRng::from_entropy())
            .sample_iter(Standard)
            .take(MSG_SIZE - 2)
            .collect::<Vec<_>>(),
    )
});

#[derive(Clone)]
pub struct P2PNode(pub Node);

impl Pea2Pea for P2PNode {
    fn node(&self) -> &Node {
        &self.0
    }
}

#[async_trait::async_trait]
impl Reading for P2PNode {
    type Message = bytes::Bytes;

    fn read_message<R: io::Read>(
        &self,
        _source: SocketAddr,
        reader: &mut R,
    ) -> io::Result<Option<Self::Message>> {
        let vec = crate::common::read_len_prefixed_message::<R, 2>(reader)?;
        Ok(vec.map(bytes::Bytes::from))
    }

    async fn process_message(&self, _src: SocketAddr, _msg: Self::Message) -> io::Result<()> {
        Ok(())
    }
}

impl Writing for P2PNode {
    type Message = bytes::Bytes;

    fn write_message<W: io::Write>(
        &self,
        _target: SocketAddr,
        payload: &Self::Message,
        writer: &mut W,
    ) -> io::Result<()> {
        writer.write_all(&(payload.len() as u16).to_le_bytes())?;
        writer.write_all(payload)
    }
}

impl P2PNode {
    pub async fn new<T: Into<String>>(name: T) -> Self {
        let config = Config {
            name: Some(name.into()),
            ..Default::default()
        };
        Self(Node::new(Some(config)).await.unwrap())
    }

    fn send_periodic_broadcasts(&self) {
        let self_clone = self.clone();
        tokio::spawn(async move {
            loop {
                if self_clone.node().num_connected() != 0 {
                    self_clone.send_broadcast(RANDOM_BYTES.clone()).unwrap();
                } else {
                    info!(parent: self_clone.node().span(), "meh, I have no frens to chat with",);
                }
                sleep(Duration::from_micros(1)).await;
            }
        });
    }
}

#[tokio::test]
async fn broadcast_benches_example() {
    // tracing_subscriber::fmt::init();
    // println!("{}", RANDOM_BYTES.len());

    let random_nodes = common::start_nodes(4, None)
        .await
        .into_iter()
        .map(P2PNode)
        .collect::<Vec<_>>();
    for rando in &random_nodes {
        rando.enable_reading().await;
    }

    let broadcaster = P2PNode::new("chatty").await;

    broadcaster.enable_writing().await;
    broadcaster.send_periodic_broadcasts();

    for rando in &random_nodes {
        broadcaster
            .0
            .connect(rando.node().listening_addr().unwrap())
            .await
            .unwrap();
    }

    let now = std::time::Instant::now();
    loop {
        tokio::time::sleep(std::time::Duration::from_millis(1)).await;
        if now.elapsed() > std::time::Duration::from_secs(60) {
            break;
        }
    }

    let r = broadcaster.node().stats().sent();
    println!("broadcaster send msgs({}) bytes({})", r.0, r.1);
    for rando in &random_nodes {
        let r = rando.node().stats().received();
        println!("receiver receive msgs({}) bytes({})", r.0, r.1);
    }
}

**Comment by ljedrz** [comment]
Yes, and adjusting the `Config` would have the same effect.

**Comment by ljedrz** [comment]
> I might actually use an UnboundedChannel for the channels inside the protocols (in the handler objects), as the growth of their depth is bounded by the connection limits.

Implemented in https://github.com/ljedrz/pea2pea/commit/cacf7904af8e60befbdda7f9db9b0d8d8e1b6e73.

**Comment by ljedrz** [comment]
Closing due to the aforementioned reasons and lack of activity; as mentioned, one of the components of the PR was merged.

**Pull request closed without merging**
